SQLEXEC(gnx,"select idfactura, fecha, cuenta,total from factura GROUP BY CUENTA,IDFACTURA ORDER BY IDFACTURA","REPBANCO")

DELETE FROM REPBANCO WHERE  EMPTY(CUENTA)
SET DELETED ON


REPORT FORM repbancos PREVIEW 
